export enum FirebaseColumns{
    USERS = "USERS",
    PASSWORD_RESET_REQUESTS = "PASSWORD_RESET_REQUESTS",
    VERIFICATION_REQUESTS= "VERIFICATION_REQUESTS",
    RESTAURANT_MENUS = "RESTAURANT_MENUS",
}