export enum FirebaseColumns{
    CUSTOMERS = "CUSTOMERS",
    RESTAURANTS = "RESTAURANTS",
    PASSWORD_RESET_REQUESTS = "PASSWORD_RESET_REQUESTS",
    VERIFICATION_REQUESTS= "VERIFICATION_REQUESTS",
    RESTAURANT_MENUS = "RESTAURANT_MENUS",
    BOOSTED_MENUS = "BOOSTED_MENUS",
    SEARCH_BOOSTS="SEARCH_BOOSTS",
}